few changes
a1p4ca/herbage pull request #4
Opened 2019-07-31 14:20 UTC by wj1187

change header apply method
& add copy function
& add modify modal

2019-08-01 12:27 UTC, seompark requested changes

2019-08-01 12:27 UTC, a1p4ca commented on www/pages/index.js
두번째 인자로 [] 넣어야댐

2019-08-01 12:27 UTC, a1p4ca commented on www/pages/index.js
> +  const [hasNext, setHasNext] = scrollHook[0]
hasNext를 왜 이걸로 받음? fetchedPosts에 hasNext 있잖아

2019-08-01 12:27 UTC, a1p4ca commented on www/pages/index.js
> -  const [hasNext, setHasNext] = useState(postData.hasNext)
왜 얘를 infiniteScroll 쪽으류 넘김?

2019-08-01 12:50 UTC, wj1187 commented on www/pages/index.js
ㄴㄴ

2019-08-01 12:51 UTC, wj1187 commented on www/pages/index.js
> -  const [hasNext, setHasNext] = useState(postData.hasNext)
hasnext 넘기면서 무한스크롤 고친거임

2019-08-01 13:10 UTC, a1p4ca commented on www/pages/index.js
아니 안넣으면 다른 모든 state 업데이트 될 때마다 실행될텐뎅

2019-08-01 13:17 UTC, a1p4ca commented on www/pages/index.js
> -  const [hasNext, setHasNext] = useState(postData.hasNext)
보니까 굳이 useInfiniteScroll에서 넘겨받은 next를 다시 state로 감싸고 hasNext setHasNext를 반환해줄 필요 없이 그냥 넘겨받은 next 자체가 state니까 useEffect 두번째 인자로 next 넣어주면 같을 것 같음

2019-08-01 13:17 UTC, a1p4ca commented on www/pages/index.js
> -  const [hasNext, setHasNext] = useState(postData.hasNext)
useInfiniteScroll에서 hasNext를 굳이 한번 감싸서 주는 setHasNext 쓸 필요 없다는 소리임

2019-08-01 13:17 UTC, a1p4ca commented on www/src/hooks/useInfiniteScroll.js
> +    if (!hasNext) return
여기 그냥 next 쓰는방식으로

2019-08-01 13:17 UTC, a1p4ca commented on www/src/hooks/useInfiniteScroll.js
> +  const [hasNext, setHasNext] = useState(next)
이런거 안하고

2019-08-01 13:17 UTC, a1p4ca commented on www/src/hooks/useInfiniteScroll.js
> +  return [[hasNext, setHasNext], [isFetching, setIsFetching]]
너무더럽지않니??

2019-08-03 11:24 UTC, wj1187 commented on www/src/hooks/useInfiniteScroll.js
> +  return [[hasNext, setHasNext], [isFetching, setIsFetching]]
그건 좀 ㅇㅈ

2019-08-03 11:25 UTC, wj1187 commented on www/src/hooks/useInfiniteScroll.js
> +    if (!hasNext) return
ㅇㅋ 뭔소린지 알았음

2019-08-03 11:25 UTC, wj1187 commented on www/pages/index.js
아 그르냐

2019-08-06 14:46 UTC, merged